Iter9
JohnRobertFord/go-plant pull request #12
Opened 2024-12-23 08:37 UTC by JohnRobertFord

2024-12-24 22:36 UTC, avhitrov requested changes
Сервер не принимает gzip. Прочие шероховатости указаны в комментариях к коду.

2024-12-24 22:36 UTC, avhitrov commented on cmd/server/main.go
>  	r.Use(middleware.SetHeader("Content-Type", "text/plain"))
Мы не на каждый запрос должны отдавать в ответ `text/plain`. Запросы /update/ и /value/ в ответ выдают `application/json`.

2024-12-24 22:36 UTC, avhitrov commented on cmd/server/main.go
> +			close(ch)
Для чего нужен этот открытый и сразу закрытый канал?

2024-12-24 22:36 UTC, avhitrov commented on cmd/server/main.go
> +					time.Sleep(1 * time.Second)
default-секция не нужна. Поскольку здесь задействован for-select, то можно еще проверять контекст приложения. Или заменить всю конструкцию цикла на 
```
for range ticker.C {
    server.Write2File(m)
}
```

2024-12-24 22:36 UTC, avhitrov commented on internal/compress/compress.go
> +		// }
В итоге сервер умеет только отдавать gzip-содержимое. Принимать не умеет:
```
curl -v -X POST --compressed --data-binary @body-iter9.json.gz -H "Content-encoding: gzip" -H "Content-Type: application/json" http://localhost:8080/update/
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> POST /update/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.9.1
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-encoding: gzip
> Content-Type: application/json
> Content-Length: 154
>
* upload completely sent off: 154 bytes
< HTTP/1.1 400 Bad Request
< Content-Encoding: gzip
< Content-Type: text/plain
< Date: Tue, 24 Dec 2024 22:13:12 GMT
< Content-Length: 23
<
* Connection #0 to host localhost left intact
```

2024-12-24 22:36 UTC, avhitrov commented on internal/logger/logger.go
> +			panic(err)
Паника, возникающая в процессе запроса, это не очень хорошо. Учитывая то, что я не вижу restore в коде - она скорее всего приведет к падению сервера. Необходимо проверять, может ли запуститься логгер ДО того, как стартует мидлварь.

2024-12-24 22:36 UTC, avhitrov commented on internal/logger/logger.go
> +			status: 200,
Отличная информация для анализа! Что бы ни ответил пользователю сервер, в логах у нас всегда все будет хорошо. Я уже это словил, когда тестировал неработающий функционал приема gzip-содержимого.

2024-12-24 22:36 UTC, avhitrov commented on internal/server/server.go
> +		return
Вот сюда мы никогда не провалимся. Два предыдущих условия - взаимоисключающие.

2024-12-24 22:36 UTC, avhitrov commented on internal/server/server.go
> +	} else if data[0] == '[' {
Для этого в одной из следующих итераций будет отдельный эндпоинт.

2024-12-24 22:36 UTC, avhitrov commented on internal/server/server.go
> +		} else if req.Method == http.MethodPost {
Для всех этих проверок есть
- Раутер
- Конкретные хендлеры.

Пытаться в одном месте собрать все вариации ошибок по всем хендлерам - это создать еще одну точку отказа. Когда появится новый хендлер и будет забыто правило для него. И код совершенно нечитаемый.

2024-12-25 07:56 UTC, JohnRobertFord commented on cmd/server/main.go
>  	r.Use(middleware.SetHeader("Content-Type", "text/plain"))
fix (del 'r.Use(middleware.SetHeader("Content-Type", "text/plain"))')

2024-12-25 07:56 UTC, JohnRobertFord commented on cmd/server/main.go
> +			close(ch)
fix

2024-12-25 07:57 UTC, JohnRobertFord commented on cmd/server/main.go
> +					time.Sleep(1 * time.Second)
rewrite infinity loop

2024-12-25 07:58 UTC, JohnRobertFord commented on internal/compress/compress.go
> +		// }
fix (add support gzip decompress )

2024-12-25 07:58 UTC, JohnRobertFord commented on internal/logger/logger.go
> +			status: 200,
fix

2024-12-25 07:58 UTC, JohnRobertFord commented on internal/server/server.go
> +		return
fix (del it)

2024-12-25 08:04 UTC, JohnRobertFord commented on internal/server/server.go
> +	} else if data[0] == '[' {
Without this check, the 7 - test would not pass.

2024-12-25 21:33 UTC, avhitrov approved these changes
Основные косяки исправлены. В следующий итерациях рекомендую избавиться от универсальной мидлвари Middleware и раскидать валидацию по хендлерам. Проверки на соответствие запросам POST и GET раутер обычно делает под капотом.

На данный момент - аппрув.

2024-12-25 21:59 UTC, merged