Iter5
JohnRobertFord/go-plant pull request #7
Opened 2024-04-15 01:48 UTC by JohnRobertFord

2024-04-19 12:07 UTC, edylcrm requested changes

2024-04-19 12:07 UTC, edylcrm commented on cmd/server/main.go
> +func init() {
Я бы не советовал использовать эти функции без необходимости. Большое кол-во этих функций может приводить к ошибкам

2024-04-19 12:07 UTC, edylcrm commented on cmd/server/main.go
> +	mapa map[string]any
Все таки можно разделить инициализацию приложения, которая чаще всего находится в main.go и логику работы приложения которую, обычно, располагают в папке internal

2024-04-19 12:07 UTC, edylcrm commented on cmd/server/main.go
> +		mapa: make(map[string]any),
Здесь будет race condition и стоит добавить mutex

2024-04-19 12:07 UTC, edylcrm commented on cmd/server/main.go
> +		if f64, err := strconv.ParseFloat(input, 64); err == nil {
f64, i64 - такое именование не принято в golang

2024-04-19 12:07 UTC, edylcrm commented on cmd/server/main.go
> +	log.Fatal(http.ListenAndServe(envAddr, MetricRouter()))
Можно в main.go оставить функцию main и то что лежит в функции  MetricRouter(). Все остальное предлагаю вынести в internal, чтобы в дальнейшем было проще расширять функционал.

2024-04-19 12:07 UTC, edylcrm commented on cmd/server/main.go
> +	log.Fatal(http.ListenAndServe(envAddr, MetricRouter()))
Так же здесь можно добавить функционал https://pkg.go.dev/net/http#Server.Shutdown который будет корректно обрабатывать http соединения при завершении приложения.

2024-04-19 12:07 UTC, edylcrm commented on cmd/server/main.go
> +	r := chi.NewRouter()
В 1.22 стандартную библиотеку доработали. https://habr.com/ru/articles/768034/ - можно попробовать использовать ее и не использовать chi

2024-04-21 22:31 UTC, JohnRobertFord commented on cmd/server/main.go
> +	r := chi.NewRouter()
автотесты используют GO 1.21.9, поэтому новый функционал здесь использовать не получится

2024-04-22 07:41 UTC, edylcrm approved these changes

2024-04-22 21:42 UTC, merged